### ISSUE TITLE
rs2 223 js5

### ISSUE THREAD

**Issue by MatthewBishop** [openrs2/openrs2#145]
As of 223, the initial js5connection needs an additional 4 ints during the initial js5 connection (after the opcode 15 and the int revision).

Possible the class https://github.com/openrs2/openrs2/blob/master/archive/src/main/kotlin/org/openrs2/archive/cache/OsrsJs5ChannelInitializer.kt

could be modified to create a separate We could just create a separate version of https://github.com/openrs2/openrs2/blob/master/protocol/src/main/kotlin/org/openrs2/protocol/login/upstream/InitJs5RemoteConnectionCodec.kt

where the length went 4->20 and then we just write the additional ints. Not sure if this is the best approach since im not familiar with this code base, but will open a PR

**Comment by openrs2gpe** [comment]
Fixed in f472125200509a5a2f6c44ae0813a9120711b9a8
